const STATUS_VALIDATION_ERROR = 400;

const STATUS_UNAUTHORIZED_ERROR = 401;

const STATUS_NOT_FOUND = 404;

const STATUS_FORBIDDEN = 403;

const STATUS_CONFLICT = 409;

const STATUS_INTERNAL_ERROR = 500;

const STATUS_SUCCESS = 200;

const STATUS_SUCCESS_CREATED = 201;

const MONGO_DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  STATUS_VALIDATION_ERROR,
  STATUS_INTERNAL_ERROR,
  STATUS_SUCCESS,
  STATUS_SUCCESS_CREATED,
  STATUS_NOT_FOUND,
  STATUS_FORBIDDEN,
  STATUS_UNAUTHORIZED_ERROR,
  STATUS_CONFLICT,
  MONGO_DUPLICATE_ERROR_CODE,
};
